site_name: CBDB User Guide
site_description: The China Biographical Database User Guide
site_url: https://cbdb-project.github.io/cbdb-user-guide/
copyright: "© China Biographical Database Project: Harvard University, Academia Sinica, Peking University"

theme:
  name: material
  language: en
  features:
    - navigation.sections
    - navigation.expand
    - toc.integrate

plugins:
  - i18n:
      docs_structure: folder
      fallback_to_default: true
      reconfigure_material: true
      reconfigure_search: true
      languages:
        - locale: en
          default: true
          name: English
          build: true
        - locale: zh_TW
          name: 繁體中文（台灣）
          build: true
          nav_translations:
            Home: 首頁
            Main Guide: 主手冊
            Preface: 前言
            Introduction: 導論
            Chapter 1: 第 1 章
            Chapter 2: 第 2 章
            Structure of CBDB: CBDB 結構
            Summary of Tables in CBDB: CBDB 資料表總覽
            Chapter 3: 第 3 章
            Chapter 4: 第 4 章
            Appendices: 附錄
            Appendix A: 附錄 A
            Appendix B: 附錄 B
            Appendix C: 附錄 C
            Appendix D: 附錄 D
            Appendix E: 附錄 E
  - search

extra:
  generator: false

extra_javascript:
  - https://unpkg.com/mermaid@10/dist/mermaid.min.js
  - javascripts/mermaid.js
  - javascripts/continuous-ol.js

markdown_extensions:
  - fenced_code
  - footnotes
  - toc:
      permalink: true
  - tables
  - admonition
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

nav:
  - Home: index.md
  - Main Guide:
      - Preface: preface.md
      - Introduction: introduction.md
      - Chapter 1: chapter_1_relational_databases.md
      - Chapter 2:
          - Structure of CBDB: chapter_2_the_structure_of_cbdb.md
          - Summary of Tables in CBDB: chapter_2_summary_of_tables_in_cbdb.md
      - Chapter 3: chapter_3_cbdb_tools_for_analysis.md
      - Chapter 4: chapter_4_advanced_query_techniques.md
  - Appendices:
      - Appendix A: appendix_a_installing_the_ms_access_files.md
      - Appendix B: appendix_b_updating_the_visual_basic_environment.md
      - Appendix C: appendix_c_installing_the_sqlite_cbdb_on_macintosh.md
      - Appendix D: appendix_d_kinship_simplification_table.md
      - Appendix E: appendix_e_change_log_for_cbdb.md
